// <auto-generated />
using System;
using DataBaseCorrelations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBaseCorrelations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220817132653_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBaseCorrelations.Models.ItemClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItemClass");
                });

            modelBuilder.Entity("DataBaseCorrelations.Models.UserClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserClassId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ItemClassUserClass", b =>
                {
                    b.Property<Guid>("ItemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsedById")
                        .HasColumnType("uuid");

                    b.HasKey("ItemsId", "UsedById");

                    b.HasIndex("UsedById");

                    b.ToTable("ItemClassUserClass");
                });

            modelBuilder.Entity("DataBaseCorrelations.Models.UserClass", b =>
                {
                    b.HasOne("DataBaseCorrelations.Models.UserClass", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserClassId");
                });

            modelBuilder.Entity("ItemClassUserClass", b =>
                {
                    b.HasOne("DataBaseCorrelations.Models.ItemClass", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseCorrelations.Models.UserClass", null)
                        .WithMany()
                        .HasForeignKey("UsedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataBaseCorrelations.Models.UserClass", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
